### PR TITLE
feat: automatically create gem repository folder

### LINKED ISSUE #28: include data output folders as a part of git repo
**Please describe the feature**

As a developer, I want the data output folders to be automatically included so that I don't have to manually create them.

**Acceptance Criteria**

- [ ] Running the script should work without having to manually create the data output folders

**Additional context**

Currently, the ~~three~~ data output folder~~s~~ (~~`dataOverlay`, ~~`gemRepository`~~, and `neo4j`~~) needs to be manually created for first time users. It would be a better developer experience if one would not have to manually create the folder~~s~~. This could be done in a few ways, for example:
1. Adjust the script to create the folder~~s~~ automatically if they do not exist.
2. Add a `.keep` file to ~~each~~ the folder and check them into git so that they are always a part of the project.

Edit: I forgot that the `dataOverlay` and `neo4j` folders were already auto-created before. Issue updated accordingly.

### PR DESCRIPTION
**Pull request by e0**
**Related issue(s) and PR(s)**  
This PR closes #28 .

**List of changes made**  
Automatically create a folder for `gemRepository` if it doesn't already exist. This is similar to how we handle the other data output folders.

**Testing**
1. Delete the `gemRepository` folder.
2. Run the data generation, for example: `yarn start ../data-files`.
3. Verify that the `gemRepository` folder is created and the `integratedModelsTimeline.svg` file is in there.

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
@e0 the issue this PR solves also mentions 2 other folders, but I don't know if those are non-problems.

**Comment by e0** [comment]
> @e0 the issue this PR solves also mentions 2 other folders, but I don't know if those are non-problems.

Ah good point. I forgot that those folders were already being auto-created before. The issue description has been updated now.

**Review by inghylt — APPROVED** [review]
:+1:

**Review by MalinAhlberg — APPROVED** [review]
Good good!

**Pull request merged**
