### PR TITLE
style: Fix generate script to confirm to shell scripting conventions, which mostly includes style changes, but also makes it run on Alpine Linux

### LINKED ISSUE #35: generate shell script does not run on Alpine Linux
The Alpine Linux distribution uses Busybox, and its `sort` implementation does not support the long options used in the `generate` script.

### PR DESCRIPTION
**Pull request by kusalananda**
Mostly small style changes to the `generate` shell script.

One of the changes, changing the names of the option used with `sort`, makes it run on systems with Busybox `sort`, e.g. Alpine Linux (this fixes #35).

A summary of changes:

* Script does not use bash-isms, so use /bin/sh
* Quoting not needed in initial variable assignments.
* Reformat function.
* Use options with sort that are more commonly supported.
* Don't test $? separately.
* Don't call exit in function (return instead).
* Do exit from outer scope if function retuns non-zero.
* Use printf for variable data.
* Don't use curly braces when expanding variables.
* Use default path also when argument is empty (not just unset).

**Testing**
- [x] build the stack without errors
- [x] all tests should pass

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
It would be nice with a more descriptive PR name, also in the style of the conventional commits (`style: ...`).
Any clue as to why the side-by-side diff shows everything has changed?

**Comment by kusalananda** [comment]
> It would be nice with a more descriptive PR name, also in the style of the conventional commits (`style: ...`). Any clue as to why the side-by-side diff shows everything has changed?

PR title has been updated to be more descriptive.

I assume that a side-by-side diff would show that everything has changed if I managed to actually touch everything.  If you want a breakdown of the changes with individual descriptions, these are found in the individual commits and their attached commit messages.

**Comment by mihai-sysbio** [comment]
> Is it convention to _repeat_ the commit messages in the PR?

If there is only one commit in the PR, that's actually what GitHub does by default. To answer your question - not quite repeat, but summarize. That tends to yield a title closer to the issue title.

**Comment by mihai-sysbio** [comment]
I went ahead and amended the issue body with a **Testing** section, please feel free to edit it.

**Comment by mihai-sysbio** [comment]
Assuming the work in the issue has been completed, I've gone ahead and asked for reviews hoping that this PR can be merged in this sprint.

**Review by jonandernovella — APPROVED** [review]
LGTM

**Review by pdmnyberg — APPROVED** [review]
LGTM

**Pull request merged**
